/*
 * ADC_Cfg.h
 *
 * Created: 25/11/41 06:42:29 ص
 *  Author: ABDULLAH 01
 */ 


#ifndef ADC_CFG_H_
#define ADC_CFG_H_

#define VOLTAGE_REFRENCE       ADC_VREF_AVCC

#define VOLTAGE_ADJUCENT       ADC_RIGHT_ADJUST

#define ADC_CONVERSION_TRIGGER ADC_AUTO_TRIGGER

#define ADC_PRESCALER          ADC_PRESEC_128

#define ADC_INTERRUPT_STATUS   ADC_INTERRUPT_DISABLE

#define ADC_CHANNEL            ADC_CHANNEL_1


#endif /* ADC_CFG_H_ */