/*
 * External_INT_Cfg.h
 *
 * Created: 19/11/41 01:10:37 م
 *  Author: ABDULLAH 01
 */ 


#ifndef EXTERNAL_INT_CFG_H_
#define EXTERNAL_INT_CFG_H_

#define GLOBAL_INTERRUPT             GLOBAL_INTERRUPT_ENABLE
#define EXTERNAL_INT0_TRIGGER        INT0_TRIGGER_RISING_EDGE
#define EXTERNAL_INT1_TRIGGER        INT0_TRIGGER_RISING_EDGE
#define EXTERNAL_INT2_TRIGGER        INT0_TRIGGER_RISING_EDGE



#endif /* EXTERNAL_INT_CFG_H_ */